[font]
size = 12.0

[font.normal]
family = "RobotoMono Nerd Font"
style = "Regular"

[font.bold]
family = "RobotoMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "RobotoMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "RobotMono Nerd Font"
style = "Italic"

[keyboard]
bindings = [
    { key = "Back", mods = "Control", chars = "\u0017" }
]
