[manager]
show_hidden = true

[opener]
edit = [
  { run = "~/.config/yazi/nvim_yazi_wrapper.sh \"$@\"", desc = "Neovim", block = true }
]

xdg-open = [
  { run = "xdg-open \"$@\"", desc = "Open with Desktop Default" }
]

[open]
rules = [
  { mime = "text/*", use = "edit" },
  { mime = "*", use = "xdg-open" }
]

